version: "3.1"
services:
    db:
        container_name: dbs-localhost
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: default
            MYSQL_USER: marcos
            MYSQL_PASSWORD: Lilith
            MYSQL_ROOT_PASSWORD: root
#            TZ: Brazil/West
            TZ: America/Recife
        volumes:
            # - ./dumps:/docker-entrypoint-initdb.d
            - ./docker-conf/my.cnf:/etc/mysql/my.cnf
            - dbs-mysql-local:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "8800:80"
        environment:
            MYSQL_USER: marcos
            MYSQL_PASSWORD: Lilith
            MYSQL_ROOT_PASSWORD: root
volumes:
  dbs-mysql-local: